spring:
  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        enable_lazy_load_no_trans: true #Lazy Load 를 적용하기 위한 설정

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

server:
  port: 8082

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
#
#
#logging:
#  level:
#    org.hibernate.SQL: debug

---
spring:
  profiles: local

  datasource:
    dadb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@10.211.55.4:1526:NO03
      username: tmall
      password: tmall
      validation-query: select 1 from dual

---
spring:
  profiles: dev

  datasource:
    dadb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@10.40.62.151:10101:TMALL
#      DAUSER
      username: ENC(AB+1kysOd1hxLbQpzwOshw==)
      password: ENC(SRbor1pxBivq0n+Exes6tkJUKX0iS4LX)
#      TMALL
#      username: ENC(yPbM1vLi+1nHuoyuZpeOsg==)
#      password: ENC(u0CttoN5TVx7k1LTWHtw9W68Nmqg4mpy)
      validation-query: select 1 from dual

---
spring:
  profiles: stage

  datasource:
    dadb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@172.18.176.69:1525:TMALL
      username: ENC(NdRLjpiU0BLo2/XY9WCSvA==)
      password: ENC(9W0JcIEsu5NMF9a8QNnm52AT88Bq4Te7)
      validation-query: select 1 from dual


---
spring:
  profiles: product

  datasource:
    dadb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@172.28.68.78:PMETA2
#      DAUSER
      username: ENC(AOXNMtH+Qi63bbWMiS4dWg==)
      password: ENC(7MEPVGMVEhPlEO00mQHdHwI17FO4haKu)
      validation-query: select 1 from dual

    stgdb:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@172.18.176.69:1525:TMALL
      username: ENC(i0oRLcSvGC7xLwL4jV4lUQ==)
      password: ENC(FAO/eirVvEagJccWmFSUETLxXFsDXhuU)
      validation-query: select 1 from dual

